# Generated by Django 3.0.3 on 2020-03-09 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20200309_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Mat')),
            ],
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('comment', models.CharField(max_length=500)),
                ('year', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020, verbose_name='year')),
                ('cuatr', models.IntegerField(choices=[(1, '1C'), (2, '2C')])),
                ('recom', models.IntegerField(choices=[(1, 'SI'), (0, 'NO')])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Course')),
            ],
        ),
    ]
