# Generated by Django 3.0.3 on 2020-03-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_coursereview_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=500),
        ),
    ]
