# Generated by Django 3.0.3 on 2020-03-20 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20200316_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=500)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Course')),
            ],
        ),
    ]
