# Generated by Django 3.0.3 on 2020-03-20 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_adminmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminmessage',
            name='curso',
        ),
    ]
