# Generated by Django 3.0.6 on 2020-05-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_remove_adminmessage_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='flag',
            field=models.IntegerField(default=0),
        ),
    ]
